name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: xcodebuild -project 'Twier.xcodeproj' -scheme 'Twier' -destination 'platform=iOS Simulator,name=iPhone 13' test
      - name: Build
        run: xcodebuild -project 'Twier.xcodeproj' -scheme 'Twier' -destination 'generic/platform=iOS' -Configuration Release build CODE_SIGNING_ALLOWED=NO
      
